word_meanings = {
    "apple": "a round fruit with red or green skin and a whitish interior",
    "book": "a set of written or printed pages, usually bound with a protective cover",
    "car": "a four-wheeled motor vehicle used for transportation",
    "dog": "a domesticated carnivorous mammal, typically loyal and often kept as a pet",
    "tree": "a woody perennial plant, typically having a single stem or trunk",
    "house": "a building for human habitation, especially one that is lived in by a family or small group of people",
    "computer": "an electronic device for storing and processing data",
    "ocean": "a very large expanse of sea, in particular, each of the main areas into which the sea is divided geographically",
    "sun": "the star around which the earth orbits",
    "moon": "the natural satellite of the earth, visible (chiefly at night) by reflected light from the sun",
    "flower": "the seed-bearing part of a plant, consisting of reproductive organs (stamens and carpels) that are typically surrounded by a brightly colored corolla",
    "river": "a large natural stream of water flowing in a channel to the sea, a lake, or another river",
    "mountain": "a large landform that rises prominently above its surroundings, typically having a peak or summit",
    "music": "vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion",
    "friend": "a person with whom one has a bond of mutual affection",
    "love": "an intense feeling of deep affection",
    "happy": "feeling or showing pleasure or contentment",
    "sad": "feeling or showing sorrow; unhappy",
    "water": "a colorless, transparent, odorless liquid that forms the seas, lakes, rivers, and rain and is the basis of the fluids of living organisms",
    "fire": "the state of burning that produces light and heat",
    "earth": "the third planet from the sun in the solar system, orbited by the moon; the only planet known to support life",
    "air": "the invisible gaseous substance surrounding the earth, a mixture mainly of oxygen and nitrogen",
    "school": "an institution for educating children",
    "time": "the indefinite continued progress of existence and events in the past, present, and future",
    "work": "activity involving mental or physical effort done to achieve a result",
    "play": "engage in activity for enjoyment and recreation rather than a serious or practical purpose",
    "eat": "put (food) into the mouth and chew and swallow it",
    "drink": "take (a liquid) into the mouth and swallow",
    "sleep": "a condition of body and mind that typically recurs for several hours every night, in which the nervous system is relatively inactive, the eyes closed, the postural muscles relaxed, and consciousness practically suspended",
    "study": "the devotion of time and attention to gaining knowledge of an academic subject, especially by means of books",
    "travel": "make a journey, typically of some length or abroad",
    "write": "mark (letters, words, or other symbols) on a surface, typically paper, with a pen, pencil, or similar implement",
    "read": "look at and comprehend the meaning of (written or printed matter) by mentally interpreting the characters or symbols of which it is composed",
    "watch": "look at or observe attentively over a period of time",
    "listen": "give one's attention to a sound",
    "speak": "say something in order to convey information, an opinion, or a feeling",
    "run": "move at a speed faster than a walk, never having both or all the feet on the ground at the same time",
    "jump": "push oneself off a surface and into the air by using the muscles in one's legs and feet",
    "swim": "propel the body through water by using the limbs",
    "drive": "operate and control the direction and speed of a motor vehicle",
    "fly": "move through the air under control",
    "buy": "acquire in exchange for money or its equivalent; purchase",
    "sell": "give or hand over (something) in exchange for money",
    "give": "freely transfer the possession of (something) to (someone); hand over to",
    "take": "lay hold of (something) with one's hands; reach for and hold",
    "table": "a piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working",
    "chair": "a separate seat for one person, typically with a back and four legs",
    "cat": "a small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws",
    "lion": "a large, powerful carnivorous feline with a golden mane, often referred to as the 'king of the jungle'",
    "elephant": "a massive herbivorous mammal with a long trunk, tusks, and large ears, native to Africa and Asia",
    "giraffe": "a tall, long-necked herbivorous mammal with distinctive spotted coat patterns, native to Africa",
    "zebra": "a medium-sized herbivorous mammal with black and white stripes, native to Africa",
    "penguin": "a flightless bird with distinctive black and white plumage, adapted for swimming",
    "dolphin": "a highly intelligent marine mammal known for its playful behavior and communication skills",
    "koala": "a small, tree-dwelling marsupial native to Australia, known for its cuddly appearance",
    "tiger": "a large carnivorous cat with a distinctive orange coat and black stripes, native to Asia",
    "panda": "a large bear-like mammal with black-and-white fur, native to China",
    "parrot": "a colorful, intelligent bird with a strong curved beak, often kept as a pet",
    "kangaroo": "a large marsupial with powerful hind legs, native to Australia, known for hopping",
    "hippopotamus": "a large herbivorous mammal with a bulky body and large mouth, native to Africa",
    "cheetah": "a fast, agile carnivorous cat with distinctive black tear marks on its face",
    "crocodile": "a large aquatic reptile with a long snout, powerful jaws, and armored scales",
    "horse": "a domesticated herbivorous mammal with hooves, often used for riding or as a work animal",
    "rhinoceros": "a large herbivorous mammal with thick skin and one or two horns on its snout",
    "bald eagle": "a large bird of prey with a white head and tail, symbolizing the United States",
    "seagull": "a medium to large bird commonly found near coastlines, with a distinctive cry",
    "whale": "a large marine mammal, some of which are known for their spectacular breaches",
    "gazelle": "a small to medium-sized antelope with a slender build, known for its speed",
    "octopus": "a soft-bodied, eight-armed marine animal known for its intelligence and dexterity",
    "snail": "a small, slow-moving mollusk with a spiral shell, often found in gardens",
    "bat": "a flying mammal with membranous wings, often active at night",
    "owl": "a nocturnal bird of prey with large eyes and a distinctive hooting sound",
    "camel": "a large, long-necked mammal with a humped back, native to desert regions",
    "jaguar": "a large, powerful carnivorous cat native to the Americas, known for its spotted coat",
    "peacock": "a large, colorful bird with an iridescent tail, known for its elaborate courtship display",
    "polar bear": "a large carnivorous bear native to the Arctic, with a thick white fur coat",
    "shark": "a large predatory fish with cartilaginous skeletons and sharp teeth",
    "turtle": "a slow-moving reptile with a protective shell, often found in both water and on land",
    "beaver": "a large, semi-aquatic rodent known for building dams and lodges",
    "gorilla": "a large, powerful ape with a broad chest and a distinctive coat, native to Africa",
    "deer": "a graceful, hoofed mammal with antlers, often found in forests",
    "hedgehog": "a small, spiny mammal with a protective coat of sharp spines",
    "frog": "a small, tailless amphibian with smooth or warty skin, known for its hopping",
    "chimpanzee": "an intelligent, social ape native to Africa, closely related to humans",
    "gibbon": "a small, long-armed ape native to Southeast Asia",
    "pangolin": "a scaly, nocturnal mammal with a protective keratin shell, native to Asia and Africa",
    "armadillo": "a small, armored mammal with a bony shell, native to the Americas",
    "swan": "a graceful, long-necked bird with a distinctive curved neck, often found on lakes",
    "spider": "an eight-legged arachnid known for weaving silk webs to catch prey",
    "buffalo": "a large herbivorous mammal with a massive head and curved horns, native to Africa and North America",
    "lizard": "a reptile with scaly skin, a long tail, and the ability to shed its tail for defense",
    "platypus": "a unique, egg-laying mammal with a duckbill and webbed feet, native to Australia",
    "otter": "a semi-aquatic mammal with a sleek body, webbed feet, and a long tail",
    "mongoose": "a small carnivorous mammal known for its agility and ability to hunt snakes",
    "puffin": "a seabird with a colorful beak, short wings, and the ability to dive for fish",
    "walrus": "a large marine mammal with tusks and a thick layer of blubber, native to the Arctic",
    "sofa": "a comfortable seat with a back and arms, typically for two or more people",
    "table": "a flat surface with legs, used for placing objects or as a work surface",
    "chair": "a seat with a back and four legs, typically for one person",
    "bed": "a piece of furniture for sleeping on, consisting of a mattress and a frame",
    "wardrobe": "a large cabinet for storing clothes and other personal items",
    "desk": "a piece of furniture with a flat or sloped surface for writing or working",
    "bookshelf": "a set of shelves for holding books or other items",
    "dresser": "a piece of furniture with drawers for storing clothes",
    "nightstand": "a small table or cabinet beside a bed, often used for holding a lamp or clock",
    "couch": "a long upholstered piece of furniture for sitting or lying down",
    "dining table": "a table used for eating meals",
    "coffee table": "a low table placed in front of a sofa, typically used for holding drinks or magazines",
    "chest of drawers": "a piece of furniture with multiple drawers for storing clothes",
    "ottoman": "a padded, upholstered seat or bench without a back or arms",
    "bookcase": "a piece of furniture with shelves for storing books",
    "bar stool": "a tall, narrow stool used for seating at a bar or high counter",
    "chaise lounge": "a long, upholstered chair for reclining",
    "wardrobe closet": "a tall, narrow closet for hanging clothes",
    "rocking chair": "a chair with curved legs that allows it to rock back and forth",
    "sideboard": "a piece of furniture with drawers and shelves for storing dishes and tableware",
    "bunk bed": "a type of bed in which one bed frame is stacked on top of another",
    "cabinet": "a piece of furniture with doors and shelves for storing or displaying items",
    "futon": "a sofa that can be converted into a bed",
    "hutch": "a piece of furniture with shelves or cabinets, often used for storage or display",
    "vanity table": "a dressing table with a mirror, often used for applying makeup",
    "stool": "a seat without a back or arms, typically used for seating at a counter",
    "loveseat": "a small sofa for two people",
    "console table": "a narrow table designed to be placed against a wall",
    "armchair": "a comfortable chair with side supports for the arms",
    "buffet": "a piece of furniture for holding dishes and serving food",
    "credenza": "a sideboard or cupboard, often used for storing dishes",
    "bench": "a long seat for several people, typically with a back and arms",
    "china cabinet": "a cabinet with glass doors, used for displaying china and glassware",
    "entertainment center": "a piece of furniture designed to house electronic equipment and media",
    "footstool": "a low stool used to support the feet",
    "sectional sofa": "a sofa made up of sections that can be arranged in various configurations",
    "etagere": "a piece of furniture with open shelves for displaying decorative items",
    "recliner": "an armchair with a reclining back and footrest",
    "couch bed": "a sofa that can be converted into a bed",
    "dressing table": "a table with a mirror, used for applying makeup and dressing",
    "highboy": "a tall chest of drawers on legs",
    "wine rack": "a storage unit designed for holding bottles of wine",
    "fireplace mantel": "a decorative frame or shelf around a fireplace",
    "vanity stool": "a small stool used with a vanity table",
    "pouf": "a soft, cushioned seat without arms or back",
    "bar cabinet": "a cabinet designed for storing and serving alcoholic beverages",
    "trundle bed": "a bed with a second bed on wheels that can be stored underneath",
    "soccer": "a team sport played between two teams of eleven players with a spherical ball",
    "basketball": "a team sport played on a rectangular court with a raised basket at each end",
    "tennis": "a racquet sport played between two or four players on a rectangular court",
    "football (American)": "a team sport played with an oval ball on a rectangular field marked with goalposts",
    "cricket": "a bat-and-ball game played between two teams with a 11 players",
    "baseball": "a bat-and-ball game played between two teams with four bases in a diamond shape",
    "golf": "a sport in which players use clubs to hit a ball into a series of holes on a course in as few strokes as possible",
    "hockey": "a sport played on ice or field, involving two teams using a puck or ball to score goals",
    "volleyball": "a team sport played with a ball over a net, with each team trying to score points",
    "rugby": "a contact team sport played with an oval ball, usually between two teams of 15 players",
    "swimming": "an individual or team sport in which participants swim in water to compete",
    "boxing": "a combat sport in which two people engage in a contest of strength, speed, and endurance",
    "athletics (track and field)": "a collection of sports events, including running, jumping, throwing, and walking",
    "cycling": "a sport involving the riding of bicycles, either for recreation or competition",
    "table tennis": "a sport played with a lightweight ball and small paddles on a rectangular table divided by a net",
    "badminton": "a racquet sport played with a shuttlecock, either as singles or doubles",
    "skiing": "a winter sport where participants slide over snow on skis",
    "snowboarding": "a winter sport where participants ride a snowboard down a snow-covered slope",
    "surfing": "a water sport in which participants ride on the forward face of a wave",
    "athletics (field events)": "sports events that involve jumping, throwing, and other field-based activities",
    "wrestling": "a combat sport involving grappling-type techniques such as clinch fighting and pinning",
    "gymnastics": "a sport involving exercises and performances requiring physical strength, flexibility, and balance",
    "archery": "a sport involving the use of bows and arrows for shooting targets",
    "karate": "a martial art characterized by punching, kicking, and defensive blocking",
    "taekwondo": "a Korean martial art characterized by high, fast kicks and spinning and jumping kicks",
    "boxing": "a combat sport in which two people engage in a contest of strength, speed, and endurance",
    "canoeing": "a sport involving paddling a canoe or kayak, often in races on rivers or lakes",
    "rowing": "a sport involving propelling a boat on water using oars",
    "fencing": "a sport involving duels between two participants using bladed weapons",
    "golf": "a sport in which players use clubs to hit a ball into a series of holes on a course in as few strokes as possible",
    "handball": "a team sport played with a small rubber ball in which players throw the ball to each other and try to score goals",
    "horse racing": "a sport in which horses, typically thoroughbreds, race against each other",
    "ice hockey": "a team sport played on ice, in which skaters use sticks to direct a puck into the opposing team's goal",
    "judo": "a modern martial art and combat sport involving throws and ground fighting",
    "kayaking": "a sport involving paddling a small watercraft, typically in rivers or on the sea",
    "lacrosse": "a team sport played with a small rubber ball and a long-handled stick with a net",
    "marathon": "a long-distance race, typically over 26.2 miles (42.195 kilometers)",
    "mixed martial arts (MMA)": "a full-contact combat sport that allows striking and grappling",
    "netball": "a team sport similar to basketball, played with seven players each",
    "orienteering": "a sport in which participants use a map and compass to navigate through unfamiliar terrain",
    "paddleboarding": "a water sport where participants stand on a board and use a paddle to move across the water",
    "quidditch": "a fictional sport played on broomsticks in the Harry Potter series",
    "rock climbing": "a sport in which participants climb natural rock formations or artificial climbing walls",
    "sailing": "a sport involving the use of wind to propel a boat across water",
    "snooker": "a cue sport played on a rectangular table covered with a green cloth, with pockets at each corner",
    "softball": "a variant of baseball played with a larger ball on a smaller field",
    "triathlon": "a multi-sport race involving swimming, cycling, and running",
    "ultimate frisbee": "a non-contact team sport played with a flying disc (frisbee)",
    "volleyball": "a team sport played with a ball over a net, with each team trying to score points",
    "water polo": "a team sport played in water, with teams trying to score goals by throwing a ball into the opposing team's goal",
    "yachting": "a sport involving racing or cruising in yachts",
    "apple": "a round fruit with red or green skin and a whitish interior",
    "banana": "a long, curved fruit with a yellow skin and soft, sweet flesh",
    "orange": "a citrus fruit with a tough, bright orange rind and juicy, segmented flesh",
    "strawberry": "a small, red, juicy fruit with tiny seeds on the surface",
    "grape": "a small, sweet fruit that grows in clusters on vines",
    "watermelon": "a large, juicy fruit with green skin and red or pink flesh, known for its high water content",
    "kiwi": "a small, brown, fuzzy fruit with green flesh and tiny black seeds",
    "blueberry": "a small, round fruit with a blue or purple skin, typically sweet and juicy",
    "pineapple": "a tropical fruit with a tough, spiky exterior and sweet, juicy yellow flesh",
    "mango": "a tropical fruit with a smooth skin, typically yellow or orange, and sweet, juicy flesh",
    "avocado": "a green fruit with a creamy texture and a large seed in the center",
    "pear": "a sweet fruit with a thin skin, typically green or yellow, and a crisp, juicy texture",
    "peach": "a fuzzy fruit with a soft, juicy flesh and a large, hard seed in the center",
    "plum": "a small, round fruit with a smooth skin and a sweet or tart taste",
    "cherry": "a small, round fruit with a red or black skin and a single large seed",
    "apricot": "a small, orange fruit with a smooth skin and a sweet, soft flesh",
    "grapefruit": "a large, citrus fruit with a thick, yellow or pink rind and juicy, segmented flesh",
    "pomegranate": "a round fruit with a tough, outer rind and juicy, red seeds inside",
    "lemon": "a yellow citrus fruit with a sour taste and aromatic peel",
    "lime": "a green citrus fruit with a tart taste, often used in cooking and beverages",
    "cucumber": "a long, green vegetable with a mild flavor, often used in salads",
    "carrot": "a orange vegetable with a sweet flavor, often eaten raw or cooked",
    "broccoli": "a green vegetable with a dense, flowering head and stalks, often steamed or stir-fried",
    "tomato": "a red or yellow fruit with a juicy interior, often used as a vegetable in cooking",
    "bell pepper": "a sweet or spicy pepper with a green, red, yellow, or orange color",
    "spinach": "a leafy green vegetable with a mild flavor, often used in salads and cooking",
    "lettuce": "a leafy green vegetable used as the base for many salads",
    "zucchini": "a green vegetable with a mild flavor, often used in cooking and baking",
    "eggplant": "a purple or black vegetable with a spongy texture, often used in cooking",
    "sweet potato": "an orange or purple root vegetable with a sweet taste, often baked or mashed",
    "potato": "a starchy tuber with a neutral flavor, often boiled, mashed, or fried",
    "onion": "a pungent vegetable with layers of skin, often used in cooking",
    "garlic": "a pungent bulb with cloves, often used to add flavor to dishes",
    "asparagus": "a green or white vegetable with long, tender shoots, often steamed or roasted",
    "cauliflower": "a white vegetable with a compact head of undeveloped flowers, often used in cooking",
    "cabbage": "a leafy green or purple vegetable with a dense head, often used in cooking",
    "corn": "a sweet and starchy yellow vegetable often eaten as a side dish",
    "green bean": "a long, slender vegetable with a crisp texture, often steamed or sautéed",
    "pea": "a small, round green vegetable with a sweet flavor, often used in salads and cooking",
    "butternut squash": "a yellow-orange vegetable with a sweet, nutty flavor, often roasted or pureed",
    "acorn squash": "a green or orange vegetable with a distinct acorn shape, often baked or roasted",
    "pumpkin": "an orange vegetable with a thick rind and sweet, dense flesh, often used in baking",
    "radish": "a small, round vegetable with a crisp texture and a peppery flavor, often used in salads",
    "beet": "a dark red or purple vegetable with a sweet taste, often roasted or pickled",
    "celery": "a crunchy green vegetable with long stalks, often used in salads and cooking",
    "kale": "a leafy green vegetable with a slightly bitter flavor, often used in salads and cooking",
    "mushroom": "a fungus with a fleshy cap and stem, often used in cooking",
    "artichoke": "a green vegetable with a spiky outer layer and a tender heart, often steamed or grilled",
    "cantaloupe": "a sweet and juicy melon with orange flesh and a netted rind",
    "honeydew melon": "a sweet and succulent melon with pale green flesh and a smooth rind",
    "watercress": "a peppery leafy green often used in salads and sandwiches",
    "turnip": "a root vegetable with a white or purple color, often boiled or mashed",
    "rutabaga": "a root vegetable similar to a turnip but larger, often roasted or mashed",
    "blackberry": "a small, sweet and tart fruit with a dark purple or black color",
    "raspberry": "a small, sweet and tart fruit with a red or black color",
    "cranberry": "a small, tart fruit often used in sauces and beverages",
    "pomegranate": "a round fruit with a tough, outer rind and juicy, red seeds inside",
    "fig": "a sweet and chewy fruit with a thin skin and tiny seeds inside",
    "date": "a sweet and sticky fruit with a wrinkled appearance, often dried and eaten",
    "kiwi": "a small, brown, fuzzy fruit with green flesh and tiny black seeds",
    "passion fruit": "a round or oval fruit with a tough outer rind and aromatic, seed-filled flesh",
    "afghanistan": "a landlocked country in South Asia, known for its mountainous terrain",
    "albania": "a country in Southeast Europe, known for its rich history and diverse landscapes",
    "algeria": "a North African country with a diverse landscape, from deserts to mountains",
    "andorra": "a small, landlocked country in the eastern Pyrenees mountains between France and Spain",
    "angola": "a country in Southern Africa, known for its diverse culture and wildlife",
    "argentina": "a large South American country known for its tango music and dance, and beef",
    "australia": "a country and continent surrounded by the Indian and Pacific oceans, known for its unique wildlife",
    "austria": "a Central European country known for its classical music heritage and alpine scenery",
    "bahrain": "a small island country in the Persian Gulf known for its modern architecture",
    "bangladesh": "a densely populated country in South Asia, known for its rivers and deltas",
    "belgium": "a Western European country known for its medieval towns, Renaissance architecture, and chocolate",
    "brazil": "a vast South American country known for its diverse ecosystems, including the Amazon rainforest",
    "canada": "a North American country known for its vast landscapes, including mountains and lakes",
    "chile": "a South American country known for its long, narrow shape and diverse geography",
    "china": "the most populous country in the world, known for its rich history and cultural heritage",
    "colombia": "a South American country known for its diverse landscapes and vibrant culture",
    "croatia": "a European country with a long coastline along the Adriatic Sea and historic cities",
    "cuba": "a Caribbean island nation known for its reggae music, beaches, and vibrant culture",
    "czech republic": "a Central European country known for its medieval towns and castles",
    "denmark": "a Scandinavian country known for its flat landscape, bicycles, and design",
    "egypt": "a North African country known for its ancient civilization and iconic landmarks",
    "ethiopia": "a country in the Horn of Africa known for its diverse cultures and landscapes",
    "finland": "a Nordic country known for its lakes, forests, and the Northern Lights",
    "france": "a Western European country known for its art, fashion, and gastronomy",
    "germany": "a Central European country known for its history, culture, and engineering",
    "ghana": "a West African country known for its diverse wildlife, rich history, and vibrant culture",
    "greece": "a Southern European country known for its ancient history, islands, and Mediterranean cuisine",
    "greenland": "an autonomous territory within the Kingdom of Denmark, known for its icy landscapes",
    "honduras": "a Central American country known for its Mayan ruins, tropical rainforests, and beaches",
    "hungary": "a Central European country known for its thermal baths and historic architecture",
    "iceland": "a Nordic island country known for its glaciers, geysers, and hot springs",
    "india": "a South Asian country known for its diverse cultures, religions, and landscapes",
    "indonesia": "a Southeast Asian country known for its islands, beaches, and rich biodiversity",
    "iran": "a country in Western Asia known for its ancient history and cultural heritage",
    "ireland": "an island country in Northwestern Europe known for its lush landscapes and friendly people",
    "israel": "a Middle Eastern country known for its historic sites, diverse culture, and cuisine",
    "italy": "a Southern European country known for its art, architecture, and delicious food",
    "jamaica": "a Caribbean island nation known for its reggae music, beaches, and vibrant culture",
    "japan": "an East Asian country known for its advanced technology, cherry blossoms, and sushi",
    "jordan": "a Middle Eastern country known for its ancient ruins and desert landscapes",
    "kenya": "an East African country known for its wildlife, including lions, elephants, and rhinos",
    "kuwait": "a small, wealthy country in the Arabian Peninsula known for its oil reserves",
    "lebanon": "a Middle Eastern country known for its diverse cultures, ancient ruins, and cuisine",
    "madagascar": "an island country in the Indian Ocean known for its unique wildlife",
    "malaysia": "a Southeast Asian country known for its diverse cultures, rainforests, and beaches",
    "mexico": "a North American country known for its rich history, vibrant culture, and cuisine",
    "morocco": "a North African country known for its diverse landscapes and historic cities",
    "netherlands": "a Western European country known for its flat landscapes, canals, and windmills",
    "new zealand": "a country and island nation in the southwestern Pacific Ocean known for its stunning landscapes",
    "nigeria": "a West African country known for its diverse cultures, wildlife, and oil reserves",
    "norway": "a Nordic country known for its fjords, mountains, and the Northern Lights",
    "pakistan": "a South Asian country known for its diverse landscapes and rich history",
    "panama": "a Central American country known for its canal, rainforests, and diverse wildlife",
    "peru": "a South American country known for its ancient Incan ruins and diverse ecosystems",
    "philippines": "an archipelagic country in Southeast Asia known for its beaches and coral reefs",
    "poland": "a Central European country known for its medieval architecture and rich history",
    "portugal": "a Southern European country known for its historic cities and scenic landscapes",
    "qatar": "a small, wealthy country in the Arabian Peninsula known for its modern architecture",
    "romania": "a country in Eastern Europe known for its medieval castles and diverse landscapes",
    "russia": "the largest country in the world, spanning Eastern Europe and northern Asia",
    "saudi arabia": "a Middle Eastern country known for its deserts, ancient history, and modern cities",
    "senegal": "a West African country known for its diverse cultures, music, and wildlife",
    "serbia": "a landlocked country in Southeast Europe known for its history and architecture",
    "singapore": "a city-state in Southeast Asia known for its modern architecture and diverse cuisine",
    "south africa": "a country in Southern Africa known for its diverse landscapes and wildlife",
    "south korea": "an East Asian country known for its technology, pop culture, and historic sites",
    "spain": "a Southern European country known for its art, architecture, and lively culture",
    "sri lanka": "an island country in South Asia known for its beaches, temples, and tea plantations",
    "sweden": "a Nordic country known for its forests, lakes, and design sensibilities",
    "switzerland": "a Central European country known for its alpine landscapes and financial institutions",
    "syria": "a country in Western Asia known for its ancient ruins and historic cities",
    "tanzania": "an East African country known for its diverse wildlife and landscapes",
    "thailand": "a Southeast Asian country known for its tropical beaches, temples, and vibrant cities",
    "turkey": "a transcontinental country known for its blend of Eastern and Western cultures",
    "uganda": "an East African country known for its diverse landscapes and wildlife",
    "ukraine": "a country in Eastern Europe known for its history, architecture, and fertile plains",
    "united arab emirates": "a Middle Eastern country known for its modern cities and luxury",
    "united kingdom": "a country in Northwestern Europe, known for its historic landmarks and cultural heritage",
    "united states": "a North American country known for its diverse landscapes and cultural influences",
    "uruguay": "a South American country known for its beaches, gauchos, and mate tea",
    "venezuela": "a South American country known for its oil reserves, diverse landscapes, and culture",
    "vietnam": "a Southeast Asian country known for its rich history, diverse landscapes, and cuisine",
    "yemen": "a country in the Middle East known for its ancient history and diverse landscapes",
    "zambia": "a landlocked country in Southern Africa known for its wildlife and Victoria Falls",
    "zimbabwe": "a landlocked country in Southern Africa known for its diverse landscapes and wildlife",
    "sachin tendulkar": "birth date: April 24, 1973, sport: cricket",
    "virat kohli": "birth date: November 5, 1988, sport: cricket",
    "saina nehwal": "birth date: March 17, 1990, sport: badminton",
    "p.v. sindhu": "birth date: July 5, 1995, sport: badminton",
    "milkha singh": "birth date: October 8, 1929, sport: athletics",
    "sunil gavaskar": "birth date: July 10, 1949, sport: cricket",
    "m.c. mary kom": "birth date: March 1, 1982, sport: boxing",
    "leander paes": "birth date: June 17, 1973, sport: tennis",
    "mahendra singh dhoni": "birth date: July 7, 1981, sport: cricket",
    "abhinav bindra": "birth date: September 28, 1982, sport: shooting",
    "anil kumble": "birth date: October 17, 1970, sport: cricket",
    "kapil dev": "birth date: January 6, 1959, sport: cricket",
    "rohit sharma": "birth date: April 30, 1987, sport: cricket",
    "geet sethi": "birth date: April 17, 1961, sport: snooker",
    "dhanraj pillay": "birth date: July 16, 1968, sport: hockey",
    "pankaj advani": "birth date: July 24, 1985, sport: billiards/snooker",
    "jwala gutta": "birth date: September 7, 1983, sport: badminton",
    "virender sehwag": "birth date: October 20, 1978, sport: cricket",
    "karnam malleswari": "birth date: June 1, 1975, sport: weightlifting",
    "bhaichung bhutia": "birth date: December 15, 1976, sport: football",
    "deepika kumari": "birth date: June 13, 1994, sport: archery",
    "yuvraj singh": "birth date: December 12, 1981, sport: cricket",
    "harbhajan singh": "birth date: July 3, 1980, sport: cricket",
    "viswanathan anand": "birth date: December 11, 1969, sport: chess",
    "dipa karmakar": "birth date: August 9, 1993, sport: gymnastics",
    "vijender singh": "birth date: October 29, 1985, sport: boxing",
    "gagan narang": "birth date: May 6, 1983, sport: shooting",
    "shikhar dhawan": "birth date: December 5, 1985, sport: cricket",
    "ravichandran ashwin": "birth date: September 17, 1986, sport: cricket",
    "jhulan goswami": "birth date: November 25, 1982, sport: cricket",
    "sania mirza": "birth date: November 15, 1986, sport: tennis",
    "manu bhaker": "birth date: February 18, 2002, sport: shooting",
    "hima das": "birth date: January 9, 2000, sport: athletics",
    "bajrang punia": "birth date: February 26, 1994, sport: wrestling",
    "neeraj chopra": "birth date: December 24, 1997, sport: athletics",
    "p.t. usha": "birth date: June 27, 1964, sport: athletics",
    "prakash padukone": "birth date: June 10, 1955, sport: badminton",
    "dutee chand": "birth date: February 3, 1996, sport: athletics",
    "ravindra jadeja": "birth date: December 6, 1988, sport: cricket",
    "irfan pathan": "birth date: October 27, 1984, sport: cricket",
    "kidambi srikanth": "birth date: February 7, 1993, sport: badminton",
    "yuzvendra chahal": "birth date: July 23, 1990, sport: cricket",
    "mirabai chanu": "birth date: August 8, 1994, sport: weightlifting",
    "rishabh pant": "birth date: October 4, 1997, sport: cricket",
    "cheteshwar pujara": "birth date: January 25, 1988, sport: cricket",
    "ishant sharma": "birth date: September 2, 1988, sport: cricket",
    "manika batra": "birth date: June 15, 1995, sport: table tennis",
    "b. s. chandrasekhar": "birth date: May 17, 1945, sport: cricket",
    "prithvi shaw": "birth date: November 9, 1999, sport: cricket",
    "shardul thakur": "birth date: October 16, 1991, sport: cricket",
}

def get_word_meaning(word):
    return word_meanings.get(word, "Sorry, I don't know the meaning of that word.")
