name_list = [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "argentina",
    "australia",
    "austria",
    "bahrain",
    "bangladesh",
    "belgium",
    "brazil",
    "canada",
    "chile",
    "china",
    "colombia",
    "croatia",
    "cuba",
    "czech republic",
    "denmark",
    "egypt",
    "ethiopia",
    "finland",
    "france",
    "germany",
    "ghana",
    "greece",
    "greenland",
    "honduras",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "ireland",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jordan",
    "kenya",
    "kuwait",
    "lebanon",
    "madagascar",
    "malaysia",
    "mexico",
    "morocco",
    "netherlands",
    "new zealand",
    "nigeria",
    "norway",
    "pakistan",
    "panama",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russia",
    "saudi arabia",
    "senegal",
    "serbia",
    "singapore",
    "south africa",
    "south korea",
    "spain",
    "sri lanka",
    "sweden",
    "switzerland",
    "syria",
    "tanzania",
    "thailand",
    "turkey",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe",
    "sachin tendulkar",
    "virat kohli",
    "saina nehwal",
    "p.v. sindhu",
    "milkha singh",
    "sunil gavaskar",
    "m.c. mary kom",
    "leander paes",
    "mahendra singh dhoni",
    "abhinav bindra",
    "anil kumble",
    "kapil dev",
    "rohit sharma",
    "geet sethi",
    "dhanraj pillay",
    "pankaj advani",
    "jwala gutta",
    "virender sehwag",
    "karnam malleswari",
    "bhaichung bhutia",
    "deepika kumari",
    "yuvraj singh",
    "harbhajan singh",
    "viswanathan anand",
    "dipa karmakar",
    "vijender singh",
    "gagan narang",
    "shikhar dhawan",
    "ravichandran ashwin",
    "jhulan goswami",
    "sania mirza",
    "manu bhaker",
    "hima das",
    "bajrang punia",
    "neeraj chopra",
    "p.t. usha",
    "prakash padukone",
    "dutee chand",
    "ravindra jadeja",
    "irfan pathan",
    "kidambi srikanth",
    "yuzvendra chahal",
    "mirabai chanu",
    "rishabh pant",
    "cheteshwar pujara",
    "ishant sharma",
    "manika batra",
    "b. s. chandrasekhar",
    "prithvi shaw",
    "shardul thakur"
]